services:

  nginx:
    volumes:
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - wp_wordpress_data:/var/www/html:ro
      - ./wp-content/themes:/var/www/html/wp-content/themes:ro
      - wp_uploads:/var/www/html/wp-content/uploads:ro

  mysql:
    ports: []    # No exponer MySQL al host en producción

  php-fpm:
    environment:
      WORDPRESS_DEBUG: "0"
